name: Auto Deploy Service
on:
  push:
    branches: [ master ]
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2
    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: ${{ secrets.server }}
        username: ${{ secrets.username }}
        password: ${{ secrets.password }}
    - name: Build Reporting
      run: sh .ci-message.sh ✅ 

    - name: Build failure
      if: failure()
      run: sh .ci-message.sh ❌
